### ISSUE TITLE
Empty object type is incorrect

### ISSUE THREAD

**Issue by johnnymetz** [drwpow/openapi-typescript#1004]
**Description**

Empty object type is incorrect.

| Name                 | Version                      |
|:---------------------|:-----------------------------|
| `openapi-typescript` | `6.0.3`                      |
| Node.js              | `v18.11.0`                      |
| OS + version         | `macOS 12.5.1` |

**Reproduction**

I have the following field:

```
filters:
  type: object
  default: {}  # adding or removing this "default" field generates the same result
```

which currently generates the following typescript:

```
filters?: Record<string, never>;
```

**Expected result**

In version 5.4.1, it generated the following result:

```
filters?: { [key: string]: unknown };
```

In version 6+, I'd expect the following result:

```
filters?: Record<string, unknown>;
```

**Checklist**

- [x] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/CONTRIBUTING.md))

**Comment by drwpow** [comment]
So yes this is a breaking change, and this is probably opinionated, but I believe this is correct. I’d assume the following:

- `{ "type": "object" }` → `Record<string, never>` (empty object)
- `{ "type": "object", "additionalProperties": true }` → `Record<string, unknown>`

IMO it makes more sense to be stricter rather than looser when your spec doesn’t indicate that unknown properties may be available.

However, if there’s a scenario where `additionalProperties: true` produces `Record<string, never>` then that would be a bug

**Comment by johnnymetz** [comment]
This makes sense! Closing this issue.
