### ISSUE TITLE
Bug when using `anyOf`

### ISSUE THREAD

**Issue by HiiiiD** [drwpow/openapi-typescript#1020]
**Description**

A schema containing `anyOf` that only defines `required` fields, is returning a wrong type

| Name                 | Version                      |
|:---------------------|:-----------------------------|
| `openapi-typescript` | `x.x.x`                      |
| Node.js              | `x.x.x`                      |
| OS + version         | `macOS 13, Windows 11, etc.` |

**Reproduction**
```js
const schema = {
  type: "object",
  anyOf: [
        {
            required: [
                "name"
            ]
        },
        {
            required: [
                "profileImage"
            ]
        },
    ],
    additionalProperties: false,
    type: "object",
    properties: {
        name: {
            "type": "string"
        },
        profileImage: {
            "type": "string"
        }
    }
}
```
Is currently returning
```ts
type T = {
            name?: string;
            profileImage?: string;
} & Record<string, never>;
```

**Expected result**

The expected return type should be something like:
```ts
type T = { name?: string; profileImage?: string } & ({ name: string} | { profileImage: string} | { name: string; profileImage: string } )
```

**Checklist**

- [x] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/CONTRIBUTING.md))

**Comment by Newbie012** [comment]
Found any alternative?

**Comment by drwpow** [comment]
Hm maybe this example is a bit too contrived, but even if this is a valid schema the types are ambiguous. omitting `properties` inside `anyOf` is what’s producing the `Record<string, never>` because you’re saying it can be `anyOf` an object with no properties. I think this is working as-intended.

A better alternative is to specify `properties` on the `anyOf` schema objects. If doing so still produces unexpected results I can investigate further! I’d also recommend using a [discriminator object](https://spec.openapis.org/oas/latest.html#discriminator-object) to be more explicit about when properties are (or are not) required.
