### ISSUE TITLE
--make-paths-enum is missing

### ISSUE THREAD

**Issue by Inrixia** [drwpow/openapi-typescript#1057]
After updating from `5.4.1` to `6.x.x` the argument `--make-paths-enum` is no longer working. 

As far as I can tell there is no way to get this functionality since the last update? This completely breaks this library for me making it unusable as I need path's as variables that I can actually use. 

Is there a reason why this was removed or a way to enable it in the newer version?

**Comment by drwpow** [comment]
Correct. Explanation here as to why it was removed: https://github.com/drwpow/openapi-typescript/releases/tag/v6.0.0

**Comment by laurenz-glueck** [comment]
@drwpow I just came across this change which makes it pretty hard to update to v6 if you dependent on the ApiPaths enum in you application.
Is there any workaround?
Or are you planning to bring this back at some point?

**Comment by laurenz-glueck** [comment]
@drwpow Just wanted to ask again as I didn't got a response on my previous comment...
Are there any plans to bring back the generation of the ApiPaths enum?

**Comment by laurenz-glueck** [comment]
@drwpow I took a closer look at the code and I think I understood why the option was removed...
If I understand the transformers concept correct, then the problem is that the `paths` are already used for the `transformPathsObject` transformer right?

Nevertheless, I think it's important for some users to get the ApiPaths enum. 

That's why I have created a draft PR that brings back the generation of the ApiPaths enum:
https://github.com/openapi-ts/openapi-typescript/pull/2052

The PR is definitely just a draft and probably needs some improvements...
But maybe you could take a look at it and give me your feedback?
