### ISSUE TITLE
the key in the object named `"type"` is wrong converting in TS

### ISSUE THREAD

**Issue by levensta** [drwpow/openapi-typescript#1066]
**Description**

In any object the key named "type" in the properties is converted to the primitive TS type of the same name

openapi-typescript: 6.2.1
openapi: 3.0.0

**OpenAPI**

Any OpenAPI schema with "type" property in object. Object for example:

```json
{
  "title": "LevelBanner",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "properties": {
    "type": {
      "const": "banner"
    },
    "badge": {
      "type": "string"
    },
    "heading": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "buttonText": {
      "type": "string"
    }
  },
  "required": ["type", "badge", "heading", "buttonText"],
  "type": "object"
}

```

**Generated TS**

```ts
export interface components {
  schemas: {
    /** LevelBanner */
    LevelBanner: {
      /** @constant */
      type: banner;  // TS2304: Cannot find name 'banner'.
      badge: string;
      heading: string;
      description?: string;
      buttonText: string;
    };
  };
};
```

**Expected TS**

```ts
export interface components {
  schemas: {
    /** LevelBanner */
    LevelBanner: {
      /** @constant */
      type: "banner";  // just const string
      badge: string;
      heading: string;
      description?: string;
      buttonText: string;
    };
  };
};
```

**Checklist**

- [x] My OpenAPI schema passes a validator
- [ ] I’m willing to open a PR for this (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/CONTRIBUTING.md))

**Comment by wolfy1339** [comment]
While that may be a valid schema, the `type` should be specified as `string`

That way there's no ambiguity and the output is as expected

**Comment by levensta** [comment]
> While that may be a valid schema, the `type` should be specified as `string`
> 
> That way there's no ambiguity and the output is as expected

Well, that's a good point

**Comment by mitchell-merry** [comment]
Local testing, this issue has nothing to do with the property being called `type`. It has to do with `const` being specified as a string without `type: string` specified, as @wolfy1339 correctly indentified.

The issue is here:
https://github.com/drwpow/openapi-typescript/blob/04c83795975fbba084e572e40d35c79bda905b43/src/transform/schema-object.ts#L64-L76

We only escape the string if it has `type` specified, and make no attempt to infer that it is a string otherwise.

So we call the transform again and return what was passed in:
https://github.com/drwpow/openapi-typescript/blob/04c83795975fbba084e572e40d35c79bda905b43/src/transform/schema-object.ts#L39-L46

The JSON schema that the OpenAPI schema is based on seems to agree that this should be possible: https://json-schema.org/understanding-json-schema/reference/generic.html#constant-values

**Comment by mitchell-merry** [comment]
We currently assume string for enums:
https://github.com/drwpow/openapi-typescript/blob/04c83795975fbba084e572e40d35c79bda905b43/src/transform/schema-object.ts#L85-L88

Should we do the same for `const`? This would probably break existing schemas using `const: true` or `const: 0` or something

cc @drwpow

**Comment by mitchell-merry** [comment]
Unless I'm misunderstanding something, though - [swagger-cli](https://github.com/APIDevTools/swagger-cli) claims your schema is invalid, so you should probably just add `type`.
