### ISSUE TITLE
Support more type of request body

### ISSUE THREAD

**Issue by KotoriK** [drwpow/openapi-typescript#1123]
**Description**

Currently request body that is not encoded as string will be serialize to JSON https://github.com/drwpow/openapi-fetch/blob/fabfad203c326c91d7a3107f43ab3e5be95bc4f1/src/index.ts#L130
 However JSON is not the only citizen, binary data and FormData are also widely used in practice.

**Proposal**
Improve type check, pass these objects as is:
* ArrayBuffer
* TypedArray
* DataView
* Blob and File
* URLSearchParams
* FormData

(list from https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#body)

**Checklist**

- [x] I’m willing to open a PR for this (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-fetch/blob/main/CONTRIBUTING.md))

**Comment by matthewvolk** [comment]
👋 Thanks for all the work you put into this package, @drwpow - this is an exceptionally useful library!

I wanted to ask if I could clarify your point below:

> So I’m actually starting to second-guess this feature request. While, yes, sometimes OpenAPI specs have endpoints that return non-JSON-y things like file downloads, it also is not too common. Further, there’s not really much benefit this library can provide when it comes to non-JSON objects.

I was thinking the original question was focused more on non-JSON **_request_** bodies? Your reply is more focused on response bodies... 

For example, I have a spec file that defines the following request body:
```yml
requestBody:
  content:
    multipart/form-data:
      schema:
        type: object
        properties:
          image_file:
            type: string
            format: binary
```

The typescript interface generated from [openapi-typescript](https://github.com/drwpow/openapi-typescript/tree/main/packages/openapi-typescript) turns that into:
```ts
requestBody: {
  content: {
    'multipart/form-data': {
      /** Format: binary */
      image_file?: string;
    };
  };
};
```
But ultimately at build-time, `body` is typed as `undefined`:
![Screenshot 2023-06-13 at 8 26 51 PM](https://github.com/drwpow/openapi-typescript/assets/28374851/1454f5b7-eda3-4d2f-976c-f4ebda304da2)

The API endpoint I'm trying to hit requires me to send a FormData object. Unfortunately, casting FormData as `as unknown as undefined` doesn't work either, because at runtime it is serialized into a JSON string by: https://github.com/drwpow/openapi-fetch/blob/fabfad203c326c91d7a3107f43ab3e5be95bc4f1/src/index.ts#L130

Personally, I'm a huge fan of "Improve type check, pass these objects as is" in regard to passing other types of data (not just JSON) to request bodies, like @KotoriK originally mentioned. 

Maybe I'm totally misunderstanding the thread... but regardless, if you're open to allowing request bodies of types other than just JSON, I'd be more than happy to contribute to help get that done!

**Comment by qqilihq** [comment]
We're in the same boat as @matthewvolk  - the example given is actually great, thank you! We have a very similar scenario: Multipart endpoints which contain a file property in the **request** body. From what I can see, this would require two additions:

* handling of `multipart/form-data` in `openapi-fetch` (i.e. appropriate treatment of beside the current `json` content type and serializing them via `FormData`)
* allowing to customize the mapping which is generated by `openapi-typescript` (I would expect a `Blob` instead of  `string`).

**Comment by drwpow** [comment]
`v0.3.0` introduces the [parseAs option](https://openapi-ts.pages.dev/openapi-fetch/api/#fetch-options) which lets you override the default JSON parsing. This should cover most cases.

Also see the [PR notes](https://github.com/drwpow/openapi-typescript/pull/1169) for more context on why this approach was taken.

This should take care of this issue, but please let me know if any details are missing still.

**Comment by qqilihq** [comment]
@drwpow Thank you for that - as far as I can see from the release notes this covers only the **response** direction though, right? 

Another common scenario seems to be **request** bodies with non-JSON content, like in @matthewvolk's example, such as a request which contains a file Blob to be sent within a multipart request.

**Comment by qqilihq** [comment]
@drwpow Thank you for that - as far as I can see from the release notes this covers only the response direction though, right?

Another common scenario seems to be request bodies with non-JSON content, like in @matthewvolk's example, such as a request which contains a file Blob to be sent within a multipart request.

**Comment by drwpow** [comment]
Ah thank you—I did have another item to track more flexible handling of requests. But I don’t have another issue for that, so I can use this one.

**Comment by psychedelicious** [comment]
I had a go at fixing this but the types and tests are a bit beyond me, so I'm not submitting a PR - just [applied the fix via `patch-package`](https://github.com/invoke-ai/InvokeAI/commit/836e14e31fb2dd278f6d5dba6e19ca4214b38f3c).

Thanks for your work on this library!

**Comment by thibaultcapelli** [comment]
I started to write a PR when I realised I can use the bodySerializer option as you can see in this sample test: https://github.com/drwpow/openapi-typescript/blob/main/packages/openapi-fetch/src/index.test.ts#L274-L291

**Comment by qqilihq** [comment]
@drwpow Thank you for this - looking forward to give it a try!

**Comment by nilsso** [comment]
The newly added `serializeBody` is *just* about working for me, but the multipart boundary isn't getting set in headers.

**Comment by psychedelicious** [comment]
The content type should not be manually set for formData - the browser sets it automatically.

**Comment by nilsso** [comment]
I should have said that I don't set it (and maybe I should have posted some code)
```ts
const { post } = createClient<paths>({
  baseUrl: 'http://localhost:8000/',
  mode: 'cors',
})

const foo: string
const upload_file: File

await post('/levy-upload', {
  body: {
    foo,
    upload_file,
  },
  bodySerializer (body) {
    const fd = new FormData()
    fd.append('foo', body.foo)
    fd.append('upload_file', body.upload_file)
    return fd
  },
})
```
The request that gets made is `Content-Type: application/json` and was only able to get it set by the browser was to provide a fetch that ignores the `client.post` generated headers
```ts
const { post } =  createClient<paths>({
  baseUrl: 'http://localhost:8000/',
  mode: 'cors',
  fetch: (url, init) => {
    const { headers, ...newInit } = init
    return fetch(url, newInit)
  },
})
```

**Comment by psychedelicious** [comment]
Yeah - I meant I think the library is manually setting it, not you

**Comment by nilsso** [comment]
Maybe should open an issue 🧐
