### ISSUE TITLE
Svelte custom fetch

### ISSUE THREAD

**Issue by ESchouten** [drwpow/openapi-typescript#1125]
Svelte provides a [custom fetch](https://kit.svelte.dev/docs/load#making-fetch-requests) in their load functions which you have to use in order to use SSR and their middleware handlers.
For this library Svelte is listed as supported, but I can't figure out how this Svelte fetch is used. Are there examples? Or is this underway?

**Comment by pkb-pmj** [comment]
It's currently not possible to pass `fetch` to a single request like this
```ts
const { response } = await POST("/auth/login", {
    body: form.data,
    fetch,
});
```
And it seems necessary, because the `fetch` provided by SvelteKit inherits e.g. request-specific cookies.
Or is there some other way to use it which I have not thought of? If not, I can make a PR basically right now 😄

**Comment by ESchouten** [comment]
@pkb-pmj I have not used this library (yet), but I guess you could do createClient<paths>({ baseUrl: "https://myapi.dev/v1/", fetch }) in your load function and create a client everywhere you want to fetch?

**Comment by pkb-pmj** [comment]
I can also do it e.g. in `hooks.server.ts`:
```ts
export const handle = async ({ event, resolve }) => {
    const client = createClient<paths>({
        fetch: event.fetch,
        baseUrl: "/api",
    });
    event.locals.GET = client.GET;
    event.locals.PATCH = client.PATCH;
    event.locals.POST = client.POST;
    event.locals.PUT = client.PUT;

    return await resolve(event);
};
```
But I guess I don't want to create a new client on every request, when it's very easy to modify the client to accept custom per-request `fetch`.

**Comment by drwpow** [comment]
Added [an example to the docs](https://openapi-ts.pages.dev/openapi-fetch/examples/#svelte--sveltekit) that uses the custom fetcher.

To @pkb-pmj’s suggestion of putting in `hooks.server.ts` I didn’t add to the example because I’m still not too familiar on that “magic” in order to recommend that. But PRs are welcome if you’d like to add it 🙂

> I guess I don't want to create a new client on every request

In most instances, yes, that’d probably be a concern. But I recently [added benchmarks](https://github.com/drwpow/openapi-typescript/blob/main/packages/openapi-fetch/test/index.bench.js) and the `createClient()` setup is extremely lightweight. I profiled it at 2.5M ops/s on my machine. So yes as a general rule probably best to never do work you don’t need to. But also, based on QoL, calling `createClient()` every request won’t have any practical impacts.

**Comment by pkb-pmj** [comment]
@drwpow ok, I didn't think of that lol
```ts
const client = createServerClient(fetch);
const fact = await client.GET("/fact", {
  params: {
    query: { max_length: 500 },
  },
});
```
Not much different than using `locals` (ignoring creating the client in `handle` and declaring `Locals` type in `app.d.ts`):
```ts
const fact = await locals.GET("/fact", {
  params: {
    query: { max_length: 500 },
  },
});
```
Or my custom version:
```ts
const fact = await GET("/fact", {
  fetch,
  params: {
    query: { max_length: 500 },
  },
});
```
which is objectively better in a way that realistically doesn't matter as you said, so it's a question of preference?
