### ISSUE TITLE
regular expression pattern

### ISSUE THREAD

**Issue by Darkchove** [drwpow/openapi-typescript#1153]
**Description**

_Replaced the JSONLike type with a regular expression pattern matching the JSON content types

**Checklist**

- [x] I’m willing to open a PR for this (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/CONTRIBUTING.md))

**Comment by drwpow** [comment]
I’m assuming this is for `openapi-fetch`? If so, that’s a TypeScript type, which is different from a runtime RegEx. There’s no RegEx that can run because the library works using compiled types and automatic inference.

Going to close this issue, but if I’m misunderstanding your proposal, please provide a more detailed description about what you’d like to change (along with example code) and I’d be happy to consider it!
