### ISSUE TITLE
Make docs exclusively available on the website

### ISSUE THREAD

**Issue by psychedelicious** [drwpow/openapi-typescript#1217]
**Description**

The `README` is a kind of copy-paste of certain parts of the docs website.

Updates to one need to be selectively copied to the other - I updated the docs site recently but didn't update the `README`, forgot to put the changes there too.

The docs site is a much better user experience in my opinion.

**Proposal**

How about limiting the `README` to include only what it has now up to the `Usage` section - just a summary of the app - and then a link to the docs site? 

This change would be for both `openapi-ts` and `openapi-fetch`.

**Checklist**

- [X] I’m willing to open a PR for this (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/CONTRIBUTING.md))

**Comment by drwpow** [comment]
Yup this is already the plan. The docs are just new and I wanted to spend a little more time making sure they were well-organized and complete before reducing the README.

**Comment by psychedelicious** [comment]
@drwpow 

I'm happy to...

- do an organizational pass over the docs site
- maybe spruce up some UX things, just present a few things in a more structured way
- ensure it has all content currently in the READMEs

...if you're open to a PR?

**Comment by drwpow** [comment]
I’d be open to a PR! But first, I’d like to see a proposal for the **content outline**—what pages there are, what the headings / subheadings for each page are. Otherwise an “organizational pass” may be too ambiguous of a target to hit, and may lead to noisy/annoying/frustrating review cycles (unlike code, reviewing writing has so many angles to it, from voice/tone to syntax to IA).

Also see a minor note on [#1195](https://github.com/drwpow/openapi-typescript/pull/1195#issuecomment-1629215592), but that only applies to the Node.js API docs page.
