### ISSUE TITLE
ESM is hell, how do we escape hell?

### ISSUE THREAD

**Issue by djMax** [drwpow/openapi-typescript#1346]
**Description**

I struggle to even come up with a description other than "something is wrong with openapi-fetch that causes it to be almost impossible to use in a typical Typescript project. I know this is never ending frustration for everyone, but I'm hoping perhaps someone can spot the problem. I'm using express, node20, and vitest.

**Reproduction**

Here's the TS config:

```
  "compilerOptions": {
    "lib": [
      "ES2022",
      "DOM"
    ],
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "target": "ES2022",
    "declaration": true,
    "sourceMap": true,
    "outDir": "./build",
    "incremental": true,
    "isolatedModules": true,
    "strict": true,
    "baseUrl": "./src",
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "paths": {
      "@/*": [
        "./*"
      ]
    }
  }
```

**Expected result**

Not this error:
```
The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("openapi-fetch")' call instead.
  To convert this file to an ECMAScript module, change its file extension to '.mts', or add the field `"type": "module"` to '/my-project/package.json'.ts(1479)
```

(using dynamic import doesn't help either)

**Checklist**

- [X] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-fetch/blob/main/CONTRIBUTING.md))

**Comment by drwpow** [comment]
Are you using Node in ESM mode (`"type": "module"`)? ESM is the new standard JS module that supersedes legacy CJS. It’s recommended to use ESM wherever possible. That could be what’s missing.

**Comment by djMax** [comment]
No, because my package is part of 50 others that would all have to move. It was impossible when I was using Jest, but I've switched to vitest which maybe would work better. But ESM just poops on everything it touches, unless it touches everything.

**Comment by djMax** [comment]
Yeah - I was thinking the same. I don't know why openapi-fetch seems to be the "thing that breaks" so often - I guess because you're trying to do it right and ship a flexible package...

**Comment by nicu-chiciuc** [comment]
I don't have a setup right now, but you might try to change the file extension to ".mts"
```
yourFile.ts -> yourFile.mts
```

then import this file using an `await` in some of your main functions (you probably won't be able to have a top-level await).

```someFile.ts
function main() {
     const openapiFetch = await import('openapi-fetch')
}
```

**Comment by drwpow** [comment]
Hm so I forgot we added this, but we actually do [ship a CJS build already](https://github.com/drwpow/openapi-typescript/blob/main/packages/openapi-fetch/package.json#L16). Modern versions of Node (14+) should just “work” and pick up on the right thing.

If not, it may be outdated build tooling, perhaps? Some old versions of webpack don’t follow the current spec (and honestly I haven’t used even webpack 5 so I can’t say what that does)

**Comment by marcomuser** [comment]
> No, because my package is part of 50 others that would all have to move. It was impossible when I was using Jest, but I've switched to vitest which maybe would work better. But ESM just poops on everything it touches, unless it touches everything.
Are you using openapi-fetch from a Node.js Express server without bundler? So that TS is emitting the end-output? Your tsconfig states that your project's input files are ESM but since you do not have `type: "module"` in your package.json the output files will then be CJS (see: [TS Module Documentation](https://gist.github.com/andrewbranch/79f872a8b9f0507c9c5f2641cfb3efa6#module-format-detection) . In TS 5.0, a new config flag `verbatimModuleSyntax` was introduced that requires imports/exports in the project's files to be written in the output format. I suppose if you enable that, ts would require you to write your imports/exports in CJS style, right? Could you create a second package.json just for that single package which has type: "module"?

**Comment by djMax** [comment]
Yes, that should be the case. Our service is NOT esm, thus not type: module, so we just want the CJS module to get selected. And it DOES sometimes, but not all the time. Like VSCode for example shows a pile of errors about type resolutions that don't happen at runtime.

**Comment by djMax** [comment]
Ok, so here's an example. I have updated openapi-fetch, and now it does this:

```
error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("openapi-fetch")' call instead.
  To convert this file to an ECMAScript module, change its file extension to '.mts', or add the field `"type": "module"` to '/my-project/package.json'.
```

I don't want to do either of these things, I just want it to import the cjs version. I have no idea why it won't.

**Comment by marcomuser** [comment]
Alright I had a coffee and created a tiny repo to reproduce your setup: https://github.com/marcomuser/cjsts/tree/upstream. Indeed, I ran into this exact same ts error you mentioned. In order to fix this, one has to adjust the openapi-fetch build step a tiny bit. The problem is that typescript looks for a [index.d.cts](https://github.com/marcomuser/cjsts/blob/patched-openapi-fetch/node_modules/openapi-fetch/dist/cjs/index.d.cts) file to describe the [index.cjs](https://github.com/marcomuser/cjsts/blob/patched-openapi-fetch/node_modules/openapi-fetch/dist/cjs/index.cjs) CommonJS output. Currently, openapi-fetch outputs a single index.d.ts for both the index.cjs and index.js files. This works for ESM projects but not for CommonJS projects. I fixed this in my error reproduction repo by moving the CommonJS file in its own cjs subdirectory and duplicating plus renaming the index.d.ts file to index.d.cts. Finally, I changed the exports field in openapi-fetch's package.json to point to the correct location for both ESM and CJS. Check this commit: https://github.com/marcomuser/cjsts/commit/ea1ae141edaa442f0e9a5f3af651e40c3f68bd91. I tried this setup and it works for both CJS and ESM projects!

To fix this upstream, I think we need to adjust a) the package.json and b) the tsconfig.build.json to output a cjs subdirectory and make sure that it includes both an index.cjs and an index.d.cts file.

**Comment by cbix** [comment]
In my nextjs + typescript + jest usecase, I'd get this error:
```
Cannot find module 'swr-openapi' from [...]
```
and was able to fix it by setting
**next.config.ts**:
```
transpilePackages: ['swr-openapi'],
```
**jest.config.ts**: follow [nextjs guide](https://nextjs.org/docs/app/building-your-application/testing/jest), then
```
moduleNameMapper: {
  '^swr-openapi$': '<rootDir>/node_modules/swr-openapi/dist/index.js',
},
```
