### ISSUE TITLE
TypeError: (0 , openapi_typescript_1.default) is not a function

### ISSUE THREAD

**Issue by rajibkuet07** [drwpow/openapi-typescript#1350]
**Description**
When I want to use `openapiTS` function in `NestJS` it shows `TypeError: (0 , openapi_typescript_1.default) is not a function`

_The screenshot of the specific error is_

![openapi-error](https://github.com/drwpow/openapi-typescript/assets/33764081/1d9ee016-5561-40d3-b6a0-8d1b95745d9c)

**Reproduction**

_I tried with a new nest setup. It shows a similar error in this too._

**Expected result**

_(in case it’s not obvious)_

**Checklist**

- [ ] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-fetch/blob/main/CONTRIBUTING.md))

**Comment by drwpow** [comment]
This looks like a generic CJS <> ESM error, not specific to this library. Are you using ESM mode in your package.json (`"type": "module"`)? You can also try different import methods, such as `import * as openapiTS from 'openapi-typescript'`, etc. I can’t say for sure what your problem is without knowing more about your setup, but I’m pretty sure this is not a bug and just a configuration error.

**Comment by rajibkuet07** [comment]
Thanks a lot, I have fixed the issue with adding `"esModuleInterop": true` in my tsconfig file. The issue was nestjs compatibility between CJS and ESM modules.
I am closing this issue.
