### ISSUE TITLE
Generate types from yaml file on the web?

### ISSUE THREAD

**Issue by Coconaut5** [drwpow/openapi-typescript#1389]
I have been trying to generate types from yaml files that are located online but I cannot get it to work and I'm uncertain whether or not that is a possibility? The issue is that the yaml files cannot be accessed directly from the openapi-typescript command since the url doesn't serve the raw yaml but instead initiates a download of the yaml file. Is this something that can be solved with this library? 

Excuse me if this does not belong here, I was not able to find any other forum related to this where i could ask.

**Comment by drwpow** [comment]
Usually if an endpoint downloads the file it’s because the `content-type` header isn’t `application/yaml` it’s something like `application/octet-stream`. If you can’t change the endpoint’s content-type then probably your best bet is to manually fetch it in Node.js, and convert it to a string. From there you could use `js-yaml` to parse it and feed that to openapi-typescript (note in v7 you could skip the last step and just feed a YAML string straight in)
