### ISSUE TITLE
Javascript Date Conversion as Date not as Record

### ISSUE THREAD

**Issue by LFSCamargo** [drwpow/openapi-typescript#1408]
**Description**

I'm using `https://github.com/sinclairzx81/typebox` to define my API returns and return OpenAPI documentation but it looks like, the `Date` javascript type is not supported or something because when it converts from a Date to a `Record<string, any>`

I've been wondering if there's any way to override this as a Date.

I've been using this library and I love it keep up w/ the good work

![Screenshot 2023-10-24 at 4 02 39 PM](https://github.com/drwpow/openapi-typescript/assets/44933973/f8855b44-8b9e-499e-9918-8134e7220c8d)

**Comment by drwpow** [comment]
I believe the [Node.js transform API](https://openapi-ts.pages.dev/node/#transform--posttransform) is what you’re looking for. There’s even an example on using Date.

Closing this issue in anticipation of being the answer, but let me know if I misunderstood or this is not what you need.

**Comment by darkbasic** [comment]
@drwpow but what about the integrated openapi-fetch `querySerializer`? Is it capable of serializing a Javascript `Date` object into something usable for POST/PUT api calls?

**Comment by drwpow** [comment]
@darkbasic that’s a different question from the original issue, which was about the generated types. There are 2 levels here: if you want to work with Dates then you’ll need to manually modify your generated types so that Date is accepted as a response or request from your API.

Then, yes you could provide a custom `querySerializer` to transform it back into a string using the methods chosen.

It is manual work, but OpenAPI doesn’t relate to JS in any way, so there’s no standard and it’s up to you to decide what you want

**Comment by darkbasic** [comment]
> It is manual work, but OpenAPI doesn’t relate to JS in any way

**Comment by darkbasic** [comment]
> It is manual work, but OpenAPI doesn’t relate to JS in any way

@drwpow it does in the case of openapi-fetch. I know there is no standard set in stone, but other generators provide serializers/deserializers which can be plugged in to handle these common cases, that's where I was asking if there is anything like that for openapi-fetch or if I have to write my own.

**Comment by drwpow** [comment]
openapi-fetch only supports [the querySerializers mentioned in the docs](https://openapi-ts.dev/openapi-fetch/api#queryserializer). There’s no standardized way of translating Date, so you do have to write your own.
