### ISSUE TITLE
If the response body doesn't exist, there's a runtime error thrown

### ISSUE THREAD

**Issue by cipriancaba** [drwpow/openapi-typescript#1423]
**Description**

When doing a DELETE on a `tags/{id}` in the intercom api, I get a runtime error because openapi-fetch is trying to parse the response as JSON even though the return data type is correctly inferred as never

```
 ⨯ SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (node:internal/deps/undici/undici:4553:19)
    at successSteps (node:internal/deps/undici/undici:4527:27)
    at fullyReadBody (node:internal/deps/undici/undici:1307:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async specConsumeBody (node:internal/deps/undici/undici:4536:7)
    at async coreFetch (webpack-internal:///(rsc)/../../node_modules/openapi-fetch/dist/index.js:59:64)
```

Thanks for the help

| Name                 | Version                      |
| :------------------- | :--------------------------- |
| `openapi-typescript` | `7.0.0-next.2`                      |
| Node.js              | `18.20`                      |
| OS + version         | `macOS Sonoma` |

**Reproduction**

https://gist.github.com/cipriancaba/790b7366794640779f0ca662f759ef8e

`npx openapi-typescript@next intercom.yaml -o intercom.d.ts`

**Expected result**

A runtime error shouldn't be thrown 

```

**Checklist**

- [x] My OpenAPI schema passes the [Redocly validator](https://redocly.com/docs/cli/commands/lint/) (`npx @redocly/cli@latest lint`)
- [ ] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/packages/openapi-typescript/CONTRIBUTING.md))

**Comment by drwpow** [comment]
Currently, `openapi-fetch` checks for 2 things: either a `204` (no content) response, or a `Content-Length: 0` header to show there’s nothing to parse. If your DELETE endpoint returns a `200` with an empty body (which is unexpected). then `openapi-fetch` will try and parse a body expecting it to be there.

You can skip parsing by setting the `parseAs` option to `stream` or `text` ([docs](https://openapi-ts.pages.dev/openapi-fetch/api/)).

> openapi-fetch is trying to parse the response as JSON even though the return data type is correctly inferred as never

This is more of a detail most people don’t have to worry about, but openapi-fetch actually doesn’t know what your OpenAPI schema looks like at all at runtime. This is why it’s so performant. It’s a weird disconnect, but all the TS checking and type inference happens statically only in your IDE; in actual execution, it doesn’t know what should or should not be there (and it never will; if we added runtime validation it would not only bloat out the library, but it would drastically slow it down, and for most people not add any additional benefit of doing so because static typechecking is usually all most people need)

**Comment by hwwi** [comment]
@drwpow 
Is it intentional to try to parse even if the `Content-Length` header is not present?
