### ISSUE TITLE
failure on attempting to GET a binary image response

### ISSUE THREAD

**Issue by ericblade** [drwpow/openapi-typescript#1529]
**Description**

```
error: Unhandled Rejection SyntaxError: Unexpected token '�', "����►JFIF"... is not valid JSON
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (node:internal/deps/undici/undici:4747:19)
    at successSteps (node:internal/deps/undici/undici:4718:27)
    at fullyReadBody (node:internal/deps/undici/undici:1433:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async specConsumeBody (node:internal/deps/undici/undici:4727:7)
    at async coreFetch (G:\grocy-micro-ui\node_modules\openapi-fetch\dist\cjs\index.cjs:89:55)  
```
API appears to be correctly marked with "type: binary"

![image](https://github.com/drwpow/openapi-typescript/assets/1451847/c022e2ed-47a5-4272-962a-b64c8b45b442)

**Reproduction**

Attempting to get images from a grocy app server. 

**Expected result**

Should not attempt to parse JSON on type: string, format: binary

**Checklist**

- [ x ] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/packages/openapi-fetch/CONTRIBUTING.md)) ... might take me a long time to get acquainted with the code, though.  Someone who knows the repo could probably go and fix this in a second
-

**Comment by drwpow** [comment]
By default, it will always parse as JSON, but to change the behavior per-request, you can use the [parseAs](https://openapi-ts.pages.dev/openapi-fetch/api#fetch-options) option.

**Comment by drwpow** [comment]
And additional context: this library, by design, utilizes maximum performance and minimal weight by **not doing any runtime checks**. This means whatever you have in your OpenAPI specification is not read at runtime, therefore you have to manually modify behavior. If it actually kept your entire OpenAPI schema in memory at runtime, it would be hundreds of times slower and heavier (like codegen). So this sort of manual “this isn’t JSON” option is necessary in order to keep this library as lean and fast as it is.

**Comment by ericblade** [comment]
Thank you for pointing that out.

**Comment by darkbasic** [comment]
@drwpow what's the point of https://openapi-ts.dev/6.x/node#example-blob-types if you have to manually set `parseAs: 'blob'` anyway? `parseAs: 'blob'` will automatically set `data` to `Blob` anyway so...

**Comment by drwpow** [comment]
@darkbasic you’re asking about 2 different things. That’s for `openapi-typescript` which turns OpenAPI into TS types. This is a question about `openapi-fetch` that’s already been answered—openapi-fetch has no runtime awareness of what that schema is (otherwise if you included a 3 MB schema at runtime, you’d have a 3 MB or greater client).

**Comment by darkbasic** [comment]
The two things are closely related because `parseAs: 'blob'` already does the AST transform so what's the point of doing that separately if you need `parseAs: 'blob'` anyway?

**Comment by drwpow** [comment]
Always happy to answer questions but I just answered you:

> openapi-fetch has no runtime awareness of what that schema is (otherwise if you included a 3 MB schema at runtime, you’d have a 3 MB or greater client).
