### ISSUE TITLE
Request for Option to Map `OneOf` to union

### ISSUE THREAD

**Issue by koutaro-masaki** [drwpow/openapi-typescript#1589]
Implementing `OneOf` as an `XOR` type rather than a union can lead to inconvenience in scenarios like the following:

```typescript
type Foo = {
  foo: number
}
type Bar = {
  bar: string
}
const f1 = (x: XOR<Foo, Bar>) => {
  if ('foo' in x){
    x.foo satisfies number // error
  }
}
const f2 = (x: Foo | Bar) => {
  if ('foo' in x){
    x.foo satisfies number // ok
  }
}
```

This inconvenience arises because `XOR<Foo, Bar> = {foo:number; bar?: undefined} | {foo?: undefined; bar:string}` .  Having an option to map `OneOf` to a union instead of an `XOR` would help avoid such inconvenience.

Additionally, while the `XOR` type indeed prohibits assignment of variables of type `Foo & Bar`, such as `{foo:1, bar: ''}`, casting such as `{ foo:1, bar: '' } as Foo` is *safely* allowed in TypeScript. Hence, the robustness brought by the `XOR` type isn't as strong.

**Comment by drwpow** [comment]
Yeah, agreed. This would be a breaking change in 6.x but it’s just a union in 7.x. If you dig through the closed issues you’ll find lots of discussion on whether this should be OR or XOR, and there are tradeoffs and quirks of either. But all-in-all, TS handles plain unions better, and people are mostly used to the quirks, so that behavior will change in 7.x.

Going to close this issue as “already implemented” in a sense but if you try 7.x and have any feedback or bugs it’d be greatly appreciated!
