### ISSUE TITLE
SyntaxError: Type Expected

### ISSUE THREAD

**Issue by MikeYermolayev** [drwpow/openapi-typescript#377]
Hello, I'm trying to generate schema from Discourse openapi file https://docs.discourse.org/ but I get following error:

![image](https://user-images.githubusercontent.com/8783498/99853455-0856ea00-2b94-11eb-8944-2d49c140032c.png)

Any ideas? Thanks

Please note: Postman was able to load this file

**Comment by gr2m** [comment]
I don't know out of hand. The way I'd debug it is to download the `openapi.json` file and use the local file to generate `schema.ts`. Then reduce `openapi.json` to a minimum so that it still reproduces the error. Once you have that, you can start a pull request with a failing test, similar to e.g. https://github.com/drwpow/openapi-typescript/blob/ce83896df8434aa6c5d5d8baef1a6a8ff4e79c1c/tests/v3/index.test.ts#L983-L1016

Once we have that we can collaborate on fixing the problem

**Comment by MikeYermolayev** [comment]
Alright, looks like I've found the problem.

The problem occurs because this openapi file doesn't describe schema for parameters. It describes it as:
```
"/c/{id}.json": {
      "get": {
        "description": "Get a list of topics in the specified category\n",
        "tags": ["Categories"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
```

But should as

```
"/c/{id}.json": {
      "get": {
        "description": "Get a list of topics in the specified category\n",
        "tags": ["Categories"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
```


So I guess it's expected behavior

**Comment by gr2m** [comment]
I guess in that case we could set the type to `unknown`, better than failing. Could you start the PR with a failing test?

**Comment by MikeYermolayev** [comment]
Okay, I'll do it.

Maybe we can even set the type to `string` since  every path and query parameter is in fact a string

**Comment by gr2m** [comment]
>  every path and query parameter is in fact a string

good point 👍🏼
