### ISSUE TITLE
Feature request: generate enum by one of the parameters (x-enumNames, x-enum-varnames or x-ms-enum) 

### ISSUE THREAD

**Issue by Flow013** [drwpow/openapi-typescript#622]
![изображение](https://user-images.githubusercontent.com/10944287/119983958-49fc9d80-bfda-11eb-94b7-93046048f160.png)

![изображение](https://user-images.githubusercontent.com/10944287/119984090-6e587a00-bfda-11eb-86cc-ccb0514a5f93.png)

**Comment by drwpow** [comment]
Are you able to achieve this with the [Formatter API](https://github.com/drwpow/openapi-typescript#custom-formatter)?

**Comment by weber** [comment]
can an example of the Format API implementation for Enum?

**Comment by Flow013** [comment]
> 
> 
> Are you able to achieve this with the [Formatter API](https://github.com/drwpow/openapi-typescript#custom-formatter)?

Enum should be created at the lowest level, and I'm not sure that this can be done using the API Formatter.
In theory, I can create an object as a enum, but it will be difficult to use later. https://www.typescriptlang.org/docs/handbook/enums.html#objects-vs-enums

**Comment by drwpow** [comment]
There are improvements that have been shipped to the `format()` option (v5) as well as upcoming improvements to `transform()` and `postTransform()` options (v6), as well as a new `inject` option (v6) that lets you inject arbitrary TypeScript into the schema. Using all of the following should be sufficient for this.

As it stands, this library will always ignore `x-*` properties as they are intended to be used—for the consumer to decide how they function and not the tooling.

**Comment by acnebs** [comment]
Hey @drwpow, I tried to do this using the mentioned functions, but couldn't really see how they would work together.

In this specific case, I figured using `transform` is the main workhorse, using it to check for any `enum`s that also have an `x-enum-varNames` property, and then creating an enum (instead of a union). However enums obviously cannot be added inline, so realistically you need to use `inject` here, but inject is not available to the transform function itself, and I'm not actually aware of what enums I need to create before actually iterating through the schema.
