### ISSUE TITLE
Why 2 levels of `body`?

### ISSUE THREAD

**Issue by florian-milky** [drwpow/openapi-typescript#746]
Example of generated code:

```
  '/v2/firebase/verify-email': {
    post: {
      parameters: {
        body: {
          body?: {
            accessToken?: string;
            url?: string;
          };
        };
      };
      responses: {
        /** Default Response */
        200: unknown;
      };
    };
  };
```
Why is `body` there 2 times?

**Comment by drwpow** [comment]
I think this is more specific to your generated schema; if you look in some of the examples this isn’t doubled-up all the time. Could you post your original schema?

**Comment by MarcErdmann** [comment]
We have the same issue. It has to do with the property "name" in the OpenApi schema. In the petstore example schema used by @aurbano the property "name" is set to "body". That why is looks like there are two levels of "body".
If you change the value to be e.g. "order", you will see 
```
body: {
  order?: {
    ...
  };
};
```
This inconvenient since it is not how e.g. express + body-parser will handle the payload send in the body. The object will be at top-level und not under a key that corresponds to the property "name" of the OpenApi schema.

Is there a way to ignore the property "name" (behavior as in the official OpenApi documentation) and have the generated type not nested? @drwpow

**Comment by florian-milky** [comment]
I investigated a bit more, and indeed it comes from the Swagger v2 specs (see [docs](https://swagger.io/docs/specification/2-0/describing-request-body/)). In my case (using `fastify-swagger` to generate the schema), I am not even sure I can specify the second body level as required, which is the most annoying with the generated TS.

Looks like OpenAPI v3 is better for that case (see [docs](https://swagger.io/docs/specification/describing-request-body/)), so I will try to migrate to that version.
