### ISSUE TITLE
Does not resolve references to local files

### ISSUE THREAD

**Issue by maciejmyslinski** [drwpow/openapi-typescript#771]
Take for example [this small repo](https://github.com/dgarcia360/openapi-boilerplate) and run:
```
npx openapi-typescript src/openapi.yaml
```

That results in an error:
```
SyntaxError: Type expected. (8:12)
   6 |
   7 | export interface paths {
>  8 |   "/pets": ./resources/pets.yaml;
     |            ^
   9 |   "/pets/{petId}": ./resources/pet.yaml;
  10 | }
  11 |
```

`swagger-cli` bundles the docs properly (`swagger-cli bundle src/openapi.yaml --outfile _build/openapi.yaml --type yaml`)

**Comment by jbaez** [comment]
@maciejmyslinski  I just had the same issue, and had a quick look at the source. It looks like it's because the ref parsing (`utils.parseRef`) and remote ref loader (`load.load`) expects the ref to contain a `#` that would use for naming/locating the parts in the remote file. So currently, it doesn't seem capable of loading an entire ref.
However, in this case (when splitting a large schema into separated files) it might be easier to build the bundle with swagger-cli and create the TypeScript interfaces from the bundle, which works fine.
So in that specific example it should be something like:
```
swagger-cli bundle src/openapi.yaml --outfile _build/openapi.yaml --type yaml
npx openapi-typescript _build/openapi.yaml
```

**Comment by maciejmyslinski** [comment]
@jbaez that's what I'm doing as a workaround.
