### ISSUE TITLE
Unable to customize WARNING_MESSAGE

### ISSUE THREAD

**Issue by hcz** [drwpow/openapi-typescript#893]
Current warning message is exported but processed by `prettier`, so it is not easily replaceable

I suggest to expose the exact warning message, with the additional spaces, or to make it configurable.

```diff
 export const WARNING_MESSAGE = `/**
-* This file was auto-generated by openapi-typescript.
-* Do not make direct changes to the file.
-*/
+ * This file was auto-generated by openapi-typescript.
+ * Do not make direct changes to the file.
+ */
```

**Comment by drwpow** [comment]
Oops! This bad indentation was unintentional. I like your suggestion of customizing this. This was added as a suggestion, but I agree it should be configurable.

Fixed the spacing in https://github.com/drwpow/openapi-typescript/pull/904, and I also added a `commentHeading` option to the Node API to customize this (didn’t add it to the CLI because that felt a bit unwieldy, but open to suggestions there if anyone has ideas).

Also ⚠️ note that `WARNING_MESSAGE` was renamed to `COMMENT_HEADER` because I think that’s a better name for what this is.
