### ISSUE TITLE
Types in Typescript

### ISSUE THREAD

**Issue by stamoun** [drwpow/openapi-typescript#897]
When generating types, it would be nice when creating the `components` interface to also export a "direct" type for components whose names are typescript-friendly.

This is in reference to the comment here: https://github.com/drwpow/openapi-typescript#using-in-typescript

Basically instead of importing `components`, you'd import the type directly `Cat` in the generated typings below instead of `components["schemas"]["Cat"]`:

```
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: operations["AppController_getCats"];
  };
}

export interface components {
  schemas: {
    Cat: {
      color: string;
      /** @enum {string} */
      hair: "short" | "long" | "none";
      legs?: number;
      eyeColor: { [key: string]: unknown };
    };
  };
}

export interface operations {
  AppController_getCats: {
    parameters: {};
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Cat"][];
        };
      };
    };
  };
}

export interface external {}

```

**Comment by drwpow** [comment]
Funny enough [that’s how the original v1 worked](https://github.com/drwpow/openapi-typescript/blob/main/docs/migrating-from-v1.md) but I moved away from that because very few schemas follow TypeScript-friendly names, and maintaining such a big difference in code generation was too much work!

Further, with OpenAPI v3, [there’s more than just the `schemas` object](https://swagger.io/specification/#components-object)—there’s `reponses`, `parameters`, `examples`, `requestBodies`, etc.

I never want to turn down good ideas because I believe your suggestion does improve the DX! I do think your proposal is easier to use. However, because this would place restrictions on how OpenAPI schemas are limited, and this approach to codegen would only apply to some—not all—of the schema, for that reason I’d argue the specific suggestion as-written doesn’t align with the project goals, and I’m going to have to say this won’t be supported.

But again, good ideas are always welcome here! And please keep suggesting other changes like this that improve DX—those are always welcome 🙂.

**Comment by bgenia** [comment]
How about reexporting types from `components` as type definitions only if they have a valid name?

Something like this:
```ts
export type components = {
	schemas: {
		ValidTypeName: { id: string }
		"invalid-type-name": { id: string }
	}
}

export namespace Components {
	export namespace Schemas {
		export type ValidTypeName = components["schemas"]["ValidTypeName"]
	}
}
```
