### ISSUE TITLE
`responses.content` & `requestBody.content` types are generated incorrectly

### ISSUE THREAD

**Issue by vietanhtran16** [drwpow/openapi-typescript#929]
According to OpenAPI spec, `requestBody.content` and `responses.content` should be like [MediaTypeObject](https://spec.openapis.org/oas/v3.1.0#mediaTypeObject)
```
export interface operations {
  readonly "status#status": {
    readonly responses: {
      /** OK response. */
      readonly 200: {
        readonly content: {
          readonly "application/json": {
            schemas: {
              propertyOfResponse: ....
            },
            example: ...,
            examples: ...,
            encoding: ...
          }
        }
      }
    }
    readonly requestBody: {
      readonly content: {
        readonly "application/json": {
          schemas: {
            propertyOfRequest: ....
          },
          example: ...,
          examples: ...,
          encoding: ...
        }
      }
    }
  }
}
```
![image](https://user-images.githubusercontent.com/23372284/182080285-015056a6-12f1-4cf9-8b6d-cf8bdd5719b0.png)

But at the moment, they are being generated like this which is not following the spec
```
export interface operations {
  readonly "status#status": {
    readonly responses: {
      /** OK response. */
      readonly 200: {
        readonly content: {
          readonly "application/json": {
            propertyOfResponse: string
          }
        }
      }
    }
    readonly requestBody: {
      readonly content: {
        readonly "application/json": {
          propertyOfRequest: string
        }
      }
    }
  }
}
```
```

**Comment by drwpow** [comment]
Thanks for raising. There was a bit of back-and-forth on this a while ago, and yes the `schema` object is flattened. But that decision was made because this is _type generation_, not an actual runtime object to pull information from, so `schema` would be the only property on each content type anyway.

But is that assumption wrong? Is there something gained by adding an additional `['schema']` path in the lookup?

**Comment by drwpow** [comment]
Closing because the removal of `schema` is intentional; where it appears there are not other properties that necessitate that extra key; it’s just noise.

Please note that this library is **NOT** for parsing the raw OpenAPI spec! It’s for generating types _from_ your spec. So any deviation in structure between the original spec and the generated types are intentional.
