### ISSUE TITLE
Invalid handling of required additional properties

### ISSUE THREAD

**Issue by tkukushkin** [drwpow/openapi-typescript#931]
I have such spec:
```yaml
openapi: 3.0.3
info:
  title: attractor
  version: ''
paths:
  /ping/:
    get:
      tags:
        - service
      parameters: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: integer
                required:
                  - storage
```
`storage` property marked as required, but did not explicitly defined in properties.
`npx openapi-typescript` generates:
```ts
{
  "application/json": {
    storage: unknown;
  } & { [key: string]: number }
}
```
I expect storage to be of type `number`. json-schema specification [does not require](https://json-schema.org/draft/2020-12/json-schema-validation.html#name-required) to explicitly define specified required fields in `properties`.

**Comment by behindthebeard** [comment]
@drwpow Hey there! I didn't want to open a new issue, because I am not sure if this is a bug, or our schema is wrong.

After updating to v6 there has been a few changes introduced in our types generated.

Our (part of affected) schema looks like this:

```
        metrics:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/MetricMetadata'
```

Previously this resulted in this type:

```
            readonly metrics: {
                readonly [key: string]: components['schemas']['MetricMetadata']
            }
```

However, after the v6 update, we now have an undefined added to the possible values:

```
            readonly metrics: {
                [key: string]: components['schemas']['MetricMetadata'] | undefined
            }
```

I didn't find any info on this via Swagger, if the schema needs something here to not return `undefined`.
Thanks in advance!

**Comment by tkukushkin** [comment]
@behindthebeard I'm not very good at Typescript, but I think maybe new behaviour is more correct, for example:

```ts
const foo: {[key: string]: string} = {}
const bar = foo["a"]
```

Formally `bar` has type `string`, but actually it equals to `undefined`. Type does not match the value.
But if you know, that some properties always present, you should simply add them to `required` list.
