### ISSUE TITLE
Wrong unknown type

### ISSUE THREAD

**Issue by Fi1osof** [drwpow/openapi-typescript#936]
yml schema:
```yml
      requestBody:
        content: {}
        required: true
      security:
      - jwtAuth: []
      responses:
        '204':
          description: No response body
```

TS:
```ts
{
    parameters: {
      path: {
        /** A unique integer value identifying this schema. */
        id: number;
      };
    };
    responses: {
      /** No response body */
      204: never;
    };
    requestBody: {
      // Here TS error Member 'unknown' implicitly has an 'any' type.ts(7008)
      // And this is not valid code
      unknown;
    };
  }
```

Should be     `requestBody: never`?

**Comment by drwpow** [comment]
I think the generated output is correct, because the [spec specifies](https://swagger.io/docs/specification/describing-responses/#empty):

> **Empty Response Body**
Some responses, such as `204` No Content, have no body. To indicate the response body is empty, **do not specify a `content` for the response:**

I’m going to close the ticket as I believe that scenario is handled correctly, but if there’s a scenario not currently covered, please reopen / please provide more detail!
