### ISSUE TITLE
Make parent parameter object optional if all fields are optional

### ISSUE THREAD

**Issue by dolencd** [drwpow/openapi-typescript#940]
When a specification defines some parameters, such as: 
```
{
  "name": "id",
  "in": "path",
  "required": true,
  "type": "string"
},
{
  "name": "accept-language",
  "in": "header",
  "required": false,
  "type": "string"
}
```

The current output contains: 
```
parameters: {
    path: {
      id: string;
    };
    header: {
      "accept-language"?: string;
    };
};
```

Maybe this would be a good option rather than the default behaviour, but I'd like the `header` key in this example to be optional. This makes sense since all the fields included in it are optional and you may want to include none of them.

**Comment by drwpow** [comment]
This makes sense, and I’d argue this is expected behavior, because it means most requests likely happen without specifying those headers at all.

I don’t think this scenario would apply to all situations where this happens, but here in headers I think it’s a good improvement.

Would love a PR fixing this if someone has time.

**Comment by drwpow** [comment]
Update: this has been added in #968 and will ship with the next v6 release.
