### ISSUE TITLE
How do I generate the specified content based on the tag?

### ISSUE THREAD

**Issue by StringKe** [drwpow/openapi-typescript#952]
How to filter based on tags when only interfaces with specified tags need to be generated, and some interfaces do not need to be generated?

**Comment by drwpow** [comment]
Hey @StringKe could you provide a specific example of what you’re looking to do?

Posting your OpenAPI schema, along with what TS you’d like to see generated would be helpful.

**Comment by StringKe** [comment]
https://editor.swagger.io/ In this default case, there are three tags `pet`,`store`,`user` I don't need to generate http api with `pet` tag.

**Comment by drwpow** [comment]
I’m going to say for now **conditional generation isn’t supported by this library,** and I don’t think it will ever be. The reason is that this library generates **static types,** which are free. They cost nothing at runtime, or buildtime. There is no downside to generating types for your whole schema.

Beyond that, conditional generation is tricky, because that would basically involve **tree-shaking,** i.e. generating items with dependencies. That sort of deep-graph analysis is something this library won’t do, because it’s not only hard; it’s unnecessary (and would slow it down).

There is a `--exclude-deprecated` flag which will skip deprecated schema objects, but that was only added because that actually may cause type errors if your code is referencing something that it shouldn’t.
