### ISSUE TITLE
Generates `& { property: unknown; }` with `allOf` union

### ISSUE THREAD

**Issue by essential-randomness** [drwpow/openapi-typescript#958]
Hi,
I've created the following test file:
```yaml
components:
  schemas:
    BoardSummary:
      type: object
      properties:
        id:
          type: string
          format: uuid
        slug:
          type: string
        avatar_url:
          type: string
          format: uri-reference
      required:
        - id
        - slug
        - avatar_url
    LoggedInBoardSummary:
      allOf:
        - $ref: "#/components/schemas/BoardSummary"
        - type: object
          properties:
            muted:
              type: boolean
            pinned:
              type: boolean
      required:
        - muted
        - pinned

```

and it results in the following components generation, which seems correct to me, except for the fact that it results in an additional union with "unknown" types:

```ts
export interface components {
  schemas: {
    BoardSummary: {
      /** Format: uuid */
      id: string;
      slug: string;
      /** Format: uri-reference */
      avatar_url: string;
    };
    LoggedInBoardSummary: components["schemas"]["BoardSummary"] & {
      muted?: boolean;
      pinned?: boolean;
    } & { // <-- why is this here?
      muted: unknown;
      pinned: unknown;
    };
  };
}
```

I assume that `muted` and `pinned` not being in the original schema results in the extra union.

I've tried cloning the repo and generating the types with up-to-date code as I heard there's some 3.1 improvements coming, but it seems to result in the same issue. I've also tried playing around with `unevaluatedProperties: false`, but got the same result.

Is this a bug in the library, or do I have some incorrect assumptions? I may be willing to give a shot at fixing it, but don't know where to start.

**Comment by duggthangs** [comment]
+1 Same here. I also tried playing with discriminator and mappings, but no luck.

**Comment by drwpow** [comment]
Yes this definitely looks like a bug to me, and I’m not sure why it’s happening.

> I may be willing to give a shot at fixing it, but don't know where to start.

Take a look at [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/CONTRIBUTING.md), and beyond that I find this library is a very great usecase for TDD (i.e. write a failing test first, then change code to pass that test). Specifically, anything related to the spec like `allOf` should go ([in the core schema test](https://github.com/drwpow/openapi-typescript/blob/main/test/core/schema.test.js#L297)).

The fix, however, isn’t always straightforward, but even having a failing test in a draft PR is a great start.

Last thing—there are basically 2 kinds of code-generating libraries: _string-based_ generation and _AST-based_ generation. This library is the former, because I personally find the code to be easier to understand and write. But either way, transpiling from one language into another is always complicated, and there is never a 1:1 translation. But all that said, if you can figure out a way to change the code to pass the test, it’s probably the right answer 🙂

**Comment by essential-randomness** [comment]
Thank you so much for fixing this, I confirmed it works AFAICT :)
