### ISSUE TITLE
Error in generated ts file

### ISSUE THREAD

**Issue by FDiskas** [drwpow/openapi-typescript#973]
**Description**

I was trying to convert https://carapi.app/swagger.json

It could be related to vocab
```
https://carapi.app/api/vocab
```
<img width="981" alt="image" src="https://user-images.githubusercontent.com/468006/200171765-6a0f7836-f015-4ee7-b894-f8b5facc4274.png">

<img width="953" alt="image" src="https://user-images.githubusercontent.com/468006/200171788-e78f6c82-8a44-4321-8c3d-0b5dd75a469b.png">

| Name                 | Version                      |
|:---------------------|:-----------------------------|
| `openapi-typescript` | `^6.0.0-pre.0`                      |
| Node.js              | `v16.18.0`                      |
| OS + version         | `macOS 13` |

**Reproduction**

```
npx openapi-typescript https://carapi.app/swagger.json --output swagger.d.ts
```

**Expected result**

It should be a valid typescript file

**Checklist**

- [ ] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/CONTRIBUTING.md))

**Comment by drwpow** [comment]
Yeah this schema is unique in that it has items like:

```json
{
  "allOf": [
    { "$ref": "#/x-swagger-bake/components/schemas/Generic-Collection"" }
  ]
}
```

While that’s technically valid syntax, the `x-swagger-bake` namespace is a designated custom namespace, which means a generic tool like `openapi-typescript` doesn’t know how to interpret that.

The fix for this would be to simply ignore all `x-swagger-bake` namespaces from the generated output. It would then be up to you to add those back in, if you wanted, manually with the `transform()`/`postTransform()` hooks (v6; upcoming) or the `format()` hook (v5).

**Comment by bourquep** [comment]
I'm also facing this issue, also with the CarApi spec. Has the guidance on how do deal with this changed since 2022?
