### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'schema')

### ISSUE THREAD

**Issue by AdiPol1359** [drwpow/openapi-typescript#988]
**Description**

I have got an error in 6.0.3 version when I'm trying to generate types. When I downgraded to 5.4.1 version, everything works fine.

```
file:///Users/adrian/generator-test/node_modules/openapi-typescript/dist/load.js:140
    const currentSchema = options.schemas[schemaID].schema;
                                                    ^

TypeError: Cannot read properties of undefined (reading 'schema')
    at load (file:///Users/adrian/generator-test/node_modules/openapi-typescript/dist/load.js:140:53)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async openapiTS (file:///Users/adrian/generator-test/node_modules/openapi-typescript/dist/index.js:37:5)
    at async generateSchema (file:///Users/adrian/generator-test/node_modules/openapi-typescript/bin/cli.js:89:18)
    at async main (file:///Users/adrian/generator-test/node_modules/openapi-typescript/bin/cli.js:156:5)
```

| Name                 | Version                      |
|:---------------------|:-----------------------------|
| `openapi-typescript` | `6.0.3`                      |
| Node.js              | `18.12.1`                      |
| OS + version         | `macOS 11` |

**Reproduction**

_How can this be reproduced / when did the error occur?_

**Expected result**

_(in case it’s not obvious)_

**Checklist**

- [ ] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/CONTRIBUTING.md))

version 6.0.3:
![image](https://user-images.githubusercontent.com/27779154/201490333-1b4322c2-96a3-4f4c-80f5-73c493f7ac7e.png)

version 5.4.1:
![image](https://user-images.githubusercontent.com/27779154/201490346-953c4991-caea-47a2-a16c-5d289d61d3ff.png)

**Comment by drwpow** [comment]
Thanks for opening! Can you provide the schema that this erred on or a small reproduction of the bug?

**Comment by AdiPol1359** [comment]
> Thanks for opening! Can you provide the schema that this erred on or a small reproduction of the bug?

{"openapi":"3.0.0","paths":{"/users":{"post":{"operationId":"UsersController_createUser","parameters":[],"requestBody":{"required":true,"content":{"application/json":{"schema":{"$ref":"#/components/schemas/CreateUserDto"}}}},"responses":{"201":{"description":"The user has been created.","content":{"application/json":{"schema":{"$ref":"#/components/schemas/UserDto"}}}}},"tags":["users"]}}},"info":{"title":"Scribium API","description":"Scribium Rest API documentation.","version":"1.0.0","contact":{},"license":{"name":"MIT","url":"https://opensource.org/licenses/MIT"}},"tags":[],"servers":[],"components":{"schemas":{"CreateUserDto":{"type":"object","properties":{"email":{"type":"string","example":"john@gmail.com"},"password":{"type":"string","example":"John12345"},"fullName":{"type":"string","example":"John Smith"}},"required":["email","password","fullName"]},"UserDto":{"type":"object","properties":{"id":{"type":"number","example":10},"email":{"type":"string","example":"john@gmail.com"},"firstName":{"type":"string","example":"John"},"lastName":{"type":"string","example":"Smith","nullable":true}},"required":["id","email"]}}}}

Sure, this is my OpenAPI documentation. It's from my project: https://github.com/scribium/scribium/tree/main/apps/api

**Comment by paulintrognon** [comment]
I run into the same issue after upgrading, but the errors occurs only when the schema is remote downloaded, it works fine when the schema is retrieved locally. Maybe the way to reproduce the bug is by fetching remotely the schema @AdiPol1359 posted?

**Comment by SpazzMarticus** [comment]
Hi, I had the same problem and fixed it by adding the file extension to the url:

`npx openapi-typescript http://localhost:8080/q/openapi.yaml -o api.d.ts`

**Comment by ruslanfarutdinov** [comment]
I'm running into the same issue since upgrading. Like with others, everything works with a locally saved schema, but breaks when fetching from a server. Also using NestJS to generate the schema. Adding the `.json` extension got rid of the error, but didn't generate the typescript file correctly (it's basically empty).

**Comment by drwpow** [comment]
@AdiPol1359 thanks for that example, but I wasn’t able to recreate the bug using that schema alone. As @denosaurtrain suggested, it may have something to do with the way that schema is retrieved (e.g. if there’s no extension, or the server returns the wrong `Content-Type` header).

I’d be happy to fix the bug if someone can provide a simple reproduction of this bug in a Git repo (and not just the error message)

**Comment by yacinehmito** [comment]
I can take this bug.

**Comment by yacinehmito** [comment]
This is indeed a Content-Type issue.

The Nest endpoint does not contain a `json` extension, and its Content-Type headers follows the HTTP/2 spec, which uses only lowercase characters for headers.

Source: https://httpwg.org/specs/rfc7540.html#rfc.section.8.1.2
More context: https://blog.yaakov.online/http-2-header-casing/

Unidici's request function (and probably node's) returns the headers in a record without regard for case-insensitivity, which means that [the lookup on the `Content-Type` header](https://github.com/drwpow/openapi-typescript/blob/1fdaa2d3852ccab472dfe06c40fe82ed5dc4a9e5/src/load.ts#L134) disregards the `content-type` header.

An easy fix would be to replace Unidici's `request` by `fetch`.

@drwpow: I am tempted to make `fetch` injectable, in order to 1) make the code more portable 2) being able to mock a remote call without doing dirty tricks with `spyOn` and such. What do you think?
